name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install dependencies
        run: |
          yarn
          npx playwright install

      - name: Run tests
        id: tests
        run: yarn test
